# Generated by Django 5.1.1 on 2024-09-14 20:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='admin', max_length=20)),
                ('itemName', models.CharField(default='An Item', max_length=40)),
                ('itemCategory', models.CharField(default='A Category', max_length=40)),
                ('school', models.CharField(default='School', max_length=80)),
                ('description', models.CharField(default='Description', max_length=1000)),
                ('price', models.PositiveIntegerField(default='0', max_length=5)),
                ('imageURLs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), blank=True, default=list, size=None)),
            ],
        ),
    ]
