# Generated by Django 5.1.1 on 2024-09-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_listing_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='size',
            field=models.CharField(default='N/A', max_length=40),
        ),
    ]
